#server.port: 7305
management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/spring_boot_vanilla
    #username: admin
    #password: admin
    username: yugabyte
    password: yugabyte
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: mx.nuniez.xoco.spring.boot.vanilla.api.config.YugabyteDialect

  liquibase:
    change-log: "classpath:changelog/db.changelog-master.yaml"
    contexts: prod
  profiles:
    active: dev

  redis:
    port: 6380

#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
